version: '3.7'
services:
  seq:
    image: datalust/seq
    ports:
      - 8003:80
      - 5341:5341
    volumes:
      - ~/app/seqData:/data
    environment:
      ACCEPT_EULA: "Y"

networks:
  dcoimbra-contas-a-pagar-network:
    driver: bridge